---
settings:
  name: BlueXP remediation
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXP Dokumente zur Problembehebung
    url: "/index.html"
  - title: Versionshinweise
    url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Informieren Sie sich über Korrekturmaßnahmen für BlueXP
      url: "/concept-resource-templates.html"
    - title: Erfahren Sie mehr über das Tagging
      url: "/concept-tagging.html"
  - title: BlueXP Problembehebung nutzen
    entries:
    - title: Verwenden Sie Vorlagen, um die Ressourcenerstellung zu standardisieren
      entries:
      - title: Vorlagen für Ihre Organisation erstellen
        url: "/task-define-templates.html"
      - title: Überprüfen Sie die Ressourcen für die Einhaltung der Vorlagen
        url: "/task-check-template-compliance.html"
      - title: Vorlagen zum Erstellen von Ressourcen ausführen
        url: "/task-run-templates.html"
    - title: Organisieren Sie Ihre Ressourcen mithilfe von Tags
      entries:
      - title: Verwalten von Tags für Ihre Ressourcen
        url: "/task-using-tags.html"
  - title: Konzepte
    entries:
    - title: Vorlagenbausteine
      url: "/reference-template-building-blocks.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
